name: Interacting with LLMs - Autocoder Bot

on:
  issues:
    types: [opened, labeled, edited]

jobs:
  autocoder:
    name: Generate Code with ChatGPT
    runs-on: ubuntu-latest
    
    # Job-level condition: Execute only if the issue contains the 'autocoder-bot' label
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    permissions:
      issues: read
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
        # Executes the script while passing environment variables and positional arguments
        run: ./scripts/script.sh ${{ env.ISSUE_NUMBER }} ${{ env.REPOSITORY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/
          if-no-files-found: error

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: Display Generated Code using the ls command
        run: ls -R autocoder-artifact
